modLoader = "javafml"
loaderVersion = "[36,)"

license = "All Rights Reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId = "salamanderlib"
version = "1.16.5-1.0.0"
displayName = "SalamanderLib"

#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"

description = '''

'''

[[dependencies.salamanderlib]]
modId = "minecraft"
versionRange = "[1.16.5,1.17)"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.salamanderlib]]
modId = "forge"
versionRange = "[36,)"
mandatory = true
side = "BOTH"
ordering = "NONE"